// Code generated by protoc-gen-go.
// source: error.proto
// DO NOT EDIT!

/*
Package rpcrmq is a generated protocol buffer package.

It is generated from these files:
	error.proto

It has these top-level messages:
	ErrorMessage
*/
package rpcrmq

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ErrorMessage struct {
	Message string `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
}

func (m *ErrorMessage) Reset()                    { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string            { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()               {}
func (*ErrorMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*ErrorMessage)(nil), "rpcrmq.ErrorMessage")
}

var fileDescriptor0 = []byte{
	// 78 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2d, 0x2a, 0xca,
	0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x2a, 0x48, 0x2e, 0xca, 0x2d, 0x54,
	0xd2, 0xe0, 0xe2, 0x71, 0x05, 0x09, 0xfb, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0x49, 0x70,
	0xb1, 0x43, 0x99, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0x6e, 0x12, 0x1b, 0x58, 0xa3,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x18, 0xdc, 0xf0, 0xe9, 0x47, 0x00, 0x00, 0x00,
}
